---
- name: Deploy Wildfly
  hosts: wildfly,web_proxy
  remote_user: jboss
  become: yes
  gather_facts: no
  vars:
    epel_baseurl: https://download.fedoraproject.org/pub/epel/8/Everything/x86_64
    epel_rpm_key: https://src.fedoraproject.org/rpms/epel-release/raw/epel8/f/RPM-GPG-KEY-EPEL-8
    jboss_home_directory: /opt/jboss
    wildfly_version: 24.0.0.Final 
  environment: 
    JAVA_HOME: /usr/lib/jvm/java
    WILDFLY_VERSION: "{{ wildfly_version }}"
    WILDFLY_SHA1: 391346c9ed2772647ff07aeae39deb838ee11dcf
    JBOSS_HOME: /opt/jboss/wildfly
    LAUNCH_JBOSS_IN_BACKGROUND: true

  tasks:
    - name: Add EPEL repository
      yum_repository:
        name: epel
        description: EPEL YUM repo
        file: epel_repos
        baseurl: "{{ epel_baseurl }}"
        gpgcheck: yes

    - name: Add GPG Key
      rpm_key:
        state: present
        key: "{{ epel_rpm_key }}"

    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest

    - name: Install the required packages
      yum:
        name:
          - xmlstarlet
          - augeas
          - bsdtar
          - unzip
          - java-11-openjdk-devel
          - sudo
        state: present

    - name: "Fetch JAVA_HOME"
      shell: 'dirname $(dirname $(readlink -f $(which javac)))'
      register: java_home

    - name: Set JAVA_HOME
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^JAVA_HOME'
        line: 'JAVA_HOME={{ java_home.stdout }}'

    - name: Set JAVA_VERSION
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^JAVA_VERSION'
        line: 'JAVA_VERSION=11'

    - name: Set JDK_ID
      lineinfile:
        dest: /etc/environment
        state: present
        regexp: '^JDK_ID'
        line: 'JDK_ID=openjdk'

        
    - name: Create jboss group
      group:
        name: jboss
        state: present
        gid: 1001

    - name: Create {{ jboss_home_directory }} directory
      file:
        path: "{{ jboss_home_directory }}"
        state: directory
        mode: '0755'

    - name: Create jboss user
      user:
        name: jboss
        comment: JBoss User
        uid: 1001
        group: jboss
        home: "{{ jboss_home_directory }}"

    - name: Update ownership of {{ jboss_home_directory }}
      file:
        path: "{{ jboss_home_directory }}"
        state: directory
        recurse: yes
        owner: jboss
        group: jboss

    # Add the WildFly distribution to /opt, and make wildfly the owner of the extracted tar content
    - name: Download and Add WildFly distribution
      block:
        - name: Download tar ball
          get_url:
            url: "https://download.jboss.org/wildfly/{{ wildfly_version }}/wildfly-{{ wildfly_version }}.tar.gz"
            dest: "{{ jboss_home_directory }}/wildfly-{{ wildfly_version }}.tar.gz"

        - name: Add WildFly distribution
          shell: >
            sha1sum wildfly-$WILDFLY_VERSION.tar.gz | grep $WILDFLY_SHA1 \
            && tar xf wildfly-$WILDFLY_VERSION.tar.gz \
            && mv wildfly-$WILDFLY_VERSION $JBOSS_HOME \
            && rm -rf wildfly-$WILDFLY_VERSION.tar.gz \
            && chown -R jboss:0 ${JBOSS_HOME} \
            && chmod -R g+rw ${JBOSS_HOME}
          args:
            chdir: "{{ jboss_home_directory }}"

    
