
- name: start wildfly
  hosts: wildfly
  tasks:
    - name: make sure temporary file exist
      file:
        dest: ~/.ansible/tmp
        owner: jboss
        group: root
        mode: 0755
        state: directory
    - name: Start WildFly
      shell: nohup /opt/jboss/wildfly/bin/standalone.sh -b {{ ansible_facts['hostname'] }} -c standalone-full-ha.xml 2>&1 &
      become: yes
      become_user: jboss 