---
- name: Run JBOSS CLI and test
  hosts: slave2
  vars:
    jboss_home: "/opt/jboss/wildfly"
    target_config: "standalone-full-ha.xml"
    task_folder: tasks
    checklist:
      - name: "01_x-powered-by"
        desc: "Remove and mask informational headers."
        apply_solution: true
        reason: Mandatory
        
      - name: "02_disable_trace"
        desc: "Disable stack trace in response body."
        apply_solution: false
        reason: This instance is exempted from this rules
        
  tasks:
    - set_fact:
        compliance_issues: []
        solutions: []
    
    - name: 1st iteration checking
      include_tasks: "{{task_folder}}/{{item.name}}_check.yml"
      vars:
        param: "{{item}}"
      loop: "{{checklist}}"
        
    - name: print the issues     
      debug:
        var: compliance_issues

    - name: print the solutions     
      debug:
        var: solutions
    
    - name: Apply solution
      include_tasks: "{{task_folder}}/{{item}}_patch.yml"
      vars:
        param: "{{item}}"
      loop: "{{solutions}}"

    - name: reset compliance_issues
      set_fact:
        compliance_issues: []

    - name: 2nd iteration checking
      include_tasks: "{{task_folder}}/{{item.name}}_check.yml"
      vars:
        param: "{{item}}"
      loop: "{{checklist}}"
        
    - name: print the output     
      debug:
        var: compliance_issues

    - name: Generate HTML report
      template:
        src: templates/vulnerability_report.j2
        dest: /tmp/vulnerability_report.html
    
    - name: Fetch HTML report
      fetch:
        src: /tmp/vulnerability_report.html
        dest: /workspace/sample/vulnerability_report.html
    
   
        