---
- name: Run JBOSS CLI and test
  hosts: slave1
  vars_files: 
    - vars_file.yml
  tasks:
    - set_fact:
        compliance_issues: []
        solutions: []

    - name: "00_check_version copy cli to target host"
      template:
        src: templates/00_check_version.cli.j2
        dest: /tmp/00_check_version.cli
        mode: "0644"
        owner: jboss
        group: jboss

    - name: "00_check_version run cli"
      shell:
        cmd: "{{ jboss_home }}/bin/jboss-cli.sh --output-json --file=/tmp/00_check_version.cli"
      register: runtime_version_result

    
    - name: 1st iteration checking
      include_tasks: "{{task_folder}}/{{item.name}}_check.yml"
      vars:
        param: "{{item}}"
      loop: "{{checklist}}"
        
    - name: print the issues     
      debug:
        var: compliance_issues

    # - name: print the solutions     
    #   debug:
    #     var: solutions
    
    # - name: Apply solution
    #   include_tasks: "{{task_folder}}/{{item}}_patch.yml"
    #   vars:
    #     param: "{{item}}"
    #   loop: "{{solutions}}"

    # - name: reset compliance_issues
    #   set_fact:
    #     compliance_issues: []

    # - name: 2nd iteration checking
    #   include_tasks: "{{task_folder}}/{{item.name}}_check.yml"
    #   vars:
    #     param: "{{item}}"
    #   loop: "{{checklist}}"
        
    # - name: print the output     
    #   debug:
    #     var: compliance_issues

    - name: Generate HTML report
      template:
        src: templates/vulnerability_report.j2
        dest: /tmp/vulnerability_report.html
    
    - name: Fetch HTML report
      fetch:
        src: /tmp/vulnerability_report.html
        dest: /workspace/sample/vulnerability_report.html
    
   
        