---

- name: download wildfly
  import_playbook: plays/download_wildfly.yml

- name: install wildfly
  import_playbook: plays/install_wildfly.yml

- name: install jcliff
  import_playbook: plays/install_jcliff.yml

- name: setup wildfly
  import_playbook: plays/setup_cluster.yml

- name: start load balancer
  import_playbook: plays/start_load_balancer.yml

- name: start wildfly
  import_playbook: plays/start_wildfly.yml


