---

- name: download wildfly
  import_playbook: plays/download_wildfly.yml

- name: install wildfly
  import_playbook: plays/install_wildfly.yml

- name: install jcliff
  import_playbook: plays/install_jcliff.yml

- name: setup wildfly
  import_playbook: plays/setup_cluster.yml

- name: start load balancer
  import_playbook: plays/start_load_balancer_systemd.yml

- name: start wildfly as systemd
  import_playbook: plays/start_wildfly_systemd.yml

# - name: scan vulnerability
#   import_playbook: plays/scan_ccc.yml


